### ISSUE TITLE
Add golangci-lint config

### ISSUE THREAD

**Issue by ripa1993** [bitrockteam/caravan-cli#4]
Add in `.golangci.yml`
```
run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
```

GitHub action is already configured to run the checks. Locally can be run with `golangci-lint run` and `golangci-lint run --fix`
